console.log('hello typescript~')
console.log('hello typescript~')
console.log('hello typescript~')
console.log('hello javascript~')
console.log('hello javascript~')
console.log('hello javascript~')
console.log('hello javascript~')